// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pc2.Data;

#nullable disable

namespace pc2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250927020111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("pc2.Models.Inmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Banos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dormitorios")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("REAL");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Inmuebles", t =>
                        {
                            t.HasCheckConstraint("CK_Inmueble_MetrosCuadrados", "MetrosCuadrados > 0");

                            t.HasCheckConstraint("CK_Inmueble_Precio", "Precio > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Banos = 2,
                            Ciudad = "Lima",
                            Codigo = "DEP001",
                            Direccion = "Av. Central 123",
                            Dormitorios = 2,
                            Imagen = "dep1.jpg",
                            MetrosCuadrados = 80.0,
                            Precio = 120000.0,
                            Tipo = 0,
                            Titulo = "Departamento céntrico"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Banos = 3,
                            Ciudad = "Arequipa",
                            Codigo = "CASA002",
                            Direccion = "Calle Sur 45",
                            Dormitorios = 3,
                            Imagen = "casa2.jpg",
                            MetrosCuadrados = 150.0,
                            Precio = 250000.0,
                            Tipo = 1,
                            Titulo = "Casa familiar"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Banos = 1,
                            Ciudad = "Cusco",
                            Codigo = "OFI003",
                            Direccion = "Jr. Comercio 10",
                            Dormitorios = 0,
                            Imagen = "ofi3.jpg",
                            MetrosCuadrados = 60.0,
                            Precio = 90000.0,
                            Tipo = 2,
                            Titulo = "Oficina moderna"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Banos = 2,
                            Ciudad = "Trujillo",
                            Codigo = "LOC004",
                            Direccion = "Av. Norte 77",
                            Dormitorios = 0,
                            Imagen = "loc4.jpg",
                            MetrosCuadrados = 100.0,
                            Precio = 180000.0,
                            Tipo = 3,
                            Titulo = "Local comercial"
                        });
                });

            modelBuilder.Entity("pc2.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("InmuebleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("pc2.Models.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("InmuebleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InmuebleId");

                    b.ToTable("Visitas", t =>
                        {
                            t.HasCheckConstraint("CK_Visita_Fechas", "FechaInicio < FechaFin");
                        });
                });

            modelBuilder.Entity("pc2.Models.Reserva", b =>
                {
                    b.HasOne("pc2.Models.Inmueble", "Inmueble")
                        .WithMany("Reservas")
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("pc2.Models.Visita", b =>
                {
                    b.HasOne("pc2.Models.Inmueble", "Inmueble")
                        .WithMany("Visitas")
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("pc2.Models.Inmueble", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Visitas");
                });
#pragma warning restore 612, 618
        }
    }
}
